---
title: "NHL"
author: "Zheng Liu"
date: "6/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
library(jsonlite)

```

## R Markdown

see <https://records.nhl.com/site>.

```{r GET records}
url_get <- function(url_call){
  url_base <- "https://records.nhl.com/site/api/"
  url_full <- paste0(url_base, url_call)
  
  table <-
    url_full %>% 
    GET() %>%
    content(type = "text")%>%
    fromJSON()
  
  return(table$data)
}

reco_get <- function(ID){
  season_end <- paste0("franchise-season-records?cayenneExp=franchiseId=", ID)
  goalie_end <- paste0("franchise-goalie-records?cayenneExp=franchiseId=", ID)
  skater_end <- paste0("franchise-skater-records?cayenneExp=franchiseId=", ID)
  
  return(list(season = url_get(season_end),
              goalie = url_get(goalie_end),
              skater = url_get(skater_end))
         )
}

url_end <- "franchise"
fran <- url_get(url_end)

url_end <- "franchise-team-totals"
fran_total <- url_get(url_end)

fran_1 <- reco_get("1")

fran_1$season

fran_1$skater

fran_1$goalie

fran %>%
  select("id", "teamCommonName")

fran_total %>%
  select("teamId", "teamName")
```
```{r}

fran_total %>% 
  select(franchiseId, gamesPlayed, wins) %>%
  group_by(franchiseId) %>%
  summarise(games = sum(gamesPlayed), wins = sum(wins)) %>%
  mutate(ratio_win = wins/games) %>%
  arrange(desc(ratio_win))



```

